### ISSUE TITLE
Configuration Definition

### ISSUE THREAD

**Issue by stachu540** [stachu540/ALICE#2]
Configuration is a constant data and cannot be rewrite (until if you restart server instance). Will be supports extension (default: `*.yml`):
- `*.json`
- `*.conf`
- `*.yml`
- `*.yaml`

Examples (can be different in final release)
```yml
server:
  port: 8443
  ssl: # can be null if you dont wanna suport ssl
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: pwd
    key-alias: tomcat
    key-password: pwd
alice: # engines and modules implements `NamedObjectDelegatedState`
  engines:
    discord:
      enabled: true
      token: "" # must be defined if engine wanna be launched
      prefix: a!
  modules:
    fun: 
      enabled: false
  store: # Storage
    url: ~/alice.db # without type you need define prefix like sqlite:~/alice.db (without jdbc:)
    username: root
    password: root
    type: sqlite # supports only: sqlite, h2, mysql, pgsql, mssql
```
